vp0:
  extends:
    file: compose-defaults.yml
    service: vp
  environment:
    - CORE_PEER_ID=vp0
    - CORE_PEER_DISCOVERY_PERIOD=1s
    - CORE_SECURITY_ENROLLID=test_vp0
    - CORE_SECURITY_ENROLLSECRET=MwYpmSRjupbT
    - CORE_PEER_PKI_ECA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TCA_PADDR=membersrvc:7054
    - CORE_PEER_PKI_TLSCA_PADDR=membersrvc:7054
  ports:
    - "7050:7050"
    - "7051:7051"
#  command: sh -c "while ! nc membersrvc 7054 </dev/null; do sleep 1; done; peer node start"
  links:
    - membersrvc

membersrvc:
   image: hyperledger/fabric-membersrvc:x86_64-0.6.1-preview
   ports:
     - "7054:7054"
   environment:
       - MEMBERSRVC_CA_ACA_ENABLED=true
   command: membersrvc

server:
  build: ./idintt-fabric-module/server
  ports:
    - "8080:8080"
  environment:
    - NODE_ENV=development
    - MEMBERSRVC_ADDR=membersrvc:7054
    - PEER_ADDR=vp0:7051
    - GOPATH=/usr/src/chaincode
  volumes:
    - ./idintt-fabric-module/server/src:/usr/src/app/src
    - ./idintt-fabric-module/server/resources:/usr/src/app/resources
    - ./idintt-fabric-module/server/tsconfig.json:/usr/src/app/tsconfig.json
    - ./idintt-fabric-module/blockchain:/usr/src/blockchain
  links:
    - membersrvc
    - vp0
  command: bash -c "sleep 8; cat chaincodeId || (grunt build; npm run deploy;) && grunt"



#networks:
#  default:
#    external:
#      name: hyperledger_fabric
